name: Model Validation

on:
  schedule:
    - cron: '0 0 * * 0'  # Runs every Sunday at 00:00 UTC
  workflow_dispatch: # Allows manual triggering from the Actions tab

jobs:
  validation:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"] # You might want to stick to a primary version for validation

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Model Validation Scripts
      run: |
        python src/model_validation/run_validation.py
      env:
        ARCTICDB_URI: ${{ secrets.ARCTICDB_URI }} # Example of using secrets

    - name: Upload Validation Report (Optional)
      uses: actions/upload-artifact@v3
      with:
        name: model-validation-report
        path: reports/validation/
        if-no-files-found: ignore

    - name: Send Notification (Optional)
      if: failure()
      uses: actions/github-script@v6
      with:
        script: |
          const issue_number = context.issue.number;
          const owner = context.repo.owner;
          const repo = context.repo.repo;
          const octokit = github.getOctokit(process.env.GITHUB_TOKEN);

          await octokit.rest.issues.createComment({
            owner: owner,
            repo: repo,
            issue_number: issue_number,
            body: "⚠️ Model Validation Workflow Failed. Check the Actions tab for details.",
          });
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}